### ISSUE TITLE
Step 6 KeyError

### ISSUE THREAD

**Issue by pna059** [yezhengSTAT/mHiC#21]
Hi,
am getting this error at the step 6. The pipeline goes on, but the folder s6 remains empty:
```
Starts step 6 - assign probability to multi-reads potential alignment positions !
........
KeyError: -2147483648
Exception ignored in: 's6_em_cython.make_Zrevstruct'
Traceback (most recent call last):
  File "s6_em.py", line 88, in <module>
    main(priorPath, multiFilePath, multiKeysPath, uniFilePath, outFilePath, threshold)
KeyError: -2147483648
EM iteration :0 Time:1.7881393432617188e-05
Update Z!
update Z time:290.8311746120453
Iteration: 0 Multi-bin pair selection change number: 24914499

Update Pi!
update pi iteration time:159.57991337776184
Iteration: 0 Difference of pi: 33275.280097821524
```

**Comment by yezhengSTAT** [comment]
Sorry that I just saw you closed the issue. Did you figure out what is wrong? Would you mind sharing it here so that I can also learn from it to better help other users?

Thanks,
Ye

**Comment by pna059** [comment]
I did not figure out what the error meant. 
The content of the s6 directory seem complete:
ls s6/*
HiChIP_merged.validPairs.binPairCount.uniMulti
HiChIP_merged.validPairs.binPair.multi.mHiC
HiChIP_merged.validPairs.binPair.multi.mHiC.binPairCount.multi
...so I can proceed with subsequent analysis.
