### ISSUE TITLE
*.UNI file missing

### ISSUE THREAD

**Issue by Lila14** [yezhengSTAT/mHiC#3]
Line 33 of s4_bin.sh uses a file $validP.UNI as input. But this file doesn't exist (/data/drive1/hic_data/mhic/GM12878/GM12878_rep1.validPairs.UNI on my system) and I can't figure out which step is supposed to generate it.

**Comment by yezhengSTAT** [comment]
Hi Lila,
Yes, you are right. I was confused by the new version of s4_bin.sh with the old one that is on github right now and I have commented that command. The updated version which generates $validP.UNI will have a faster sorting, better duplicates removal algorithm, and much faster normalization. I am testing it on high resolution on GM12878 cell line and will post it once it proves to be stable.
